### ISSUE TITLE
Generated files should contain an auto-generated comment

### ISSUE THREAD

**Issue by jlourenc** [snyk/vervet#145]
Go tooling relies on an auto-generated DO NOT EDIT comment at the top of a Go file to detect that a file is auto-generated: https://github.com/golang/go/issues/41196.

In the case of `golangci-lint`, this is handy because the tool automatically skips auto-generated files that may raise issues otherwise depending on its configuration in the repo.

**Comment by cmars** [comment]
This seems to have been addressed -- at least for yaml. JSON doesn't support comments.

The templates used in `vervet generate` would be responsible for adding such a comment if they are used to generate Go file.
