### ISSUE TITLE
breaking change to getkin-openapi in minor version 0.122 from 0.120

### ISSUE THREAD

**Issue by genslein** [snyk/vervet#324]
https://github.com/getkin/kin-openapi/pull/763

Breaking change was introduced in a minor version. Don't upgrade getkin unless vervet has been upgraded to deal with this

**Comment by jgresty** [comment]
I've started a branch to upgrade it: feat/update-kin-openapi

That branch changes all the references so it compiles, however we are panicking at runtime when resolving references:
```
panic: reflect: reflect.Value.Set using value obtained using unexported field
```

If anyone wants to figure out why then go ahead.

**Comment by tinygrasshopper** [comment]
kin-openapi upgraded to latest in recent releases of vervet
