### ISSUE TITLE
Lint output is too verbose and not very actionable

### ISSUE THREAD

**Issue by cmars** [snyk/vervet#64]
Especially when overriding lint rules with info-level messages, the lint output is very verbose, it can result in hundreds of lines of output, one for each OpenAPI rule violation.

This is useful for developers fixing the issues, but for everyone else (and CI) it is a lot of noise.

`vervet lint` should have an option to summarize these messages. Bonus: roll these up and annotate CODEOWNERS.

**Comment by cmars** [comment]
@robcresswell We're currently evaluting an improved API linting tool that should show a marked improvement here (Optic CI).

**Comment by robcresswell** [comment]
Very cool, good to know!

**Comment by cmars** [comment]
Fixed in #105

**Comment by cmars** [comment]
Fix being applied to registry in #25345
