### ISSUE TITLE
Add sunset information to compiled OpenAPI

### ISSUE THREAD

**Issue by cmars** [snyk/vervet#86]
When Vervet compiles resource versions, it has a top-level view of all versions of a given resource. When a resource version is deprecated by a newer version, we can annotate the deprecated version with extensions that indicate:

* The newer version that deprecates the deprecated one. (x-snyk-deprecated-by)
* The eligible sunset date of the deprecated one, triggered by the date of the newer version. (x-snyk-sunset-eligible)

Note that the sunset date indicates when the deprecated version _may_ be removed, it does not mean that it _must or necessarily will_ be removed on that date. Post-sunset versions might stick around longer, but they don't have to, and a front-end router may stop routing requests to these.

**Comment by ianlivingstone** [comment]
There are standard headers for sending "this is deprecated, heres more information" that are standardized. We should try and adopt those as much as possible (e.g. we already do this internally, in places).

https://tools.ietf.org/id/draft-dalal-deprecation-header-01.html

**Comment by cmars** [comment]
Depends on #78, #89

**Comment by cmars** [comment]
Fixed in #90
